# Generated by Django 4.2.5 on 2023-09-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
        ('teachers', '0003_attendance_leavereportfaculty_feedbackfaculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_pdf', models.FileField(upload_to='pdfs/')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.faculty')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
    ]
