# Generated by Django 4.2.5 on 2023-09-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_assignmentsubmission_submit_assignment_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submit_assignment_pdf',
            field=models.FileField(upload_to='submission_pdfs/'),
        ),
    ]
